# Generated by Django 4.2.9 on 2024-03-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('bloodgroup', models.CharField(max_length=5)),
                ('identityproof', models.ImageField(upload_to='photos/identityproof')),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('disorder', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('organs', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
