# Generated by Django 4.2.9 on 2024-03-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organs',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organs',
            field=models.ManyToManyField(blank=True, to='Index.organ'),
        ),
    ]
